#!/usr/bin/env python
"""
Main executable for rename_seq
"""
import argparse

import rs_logging
import rename_seq
LOGGER = rs_logging.Logger.get_logger("rename_seq")


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("path", help="Path to the images folder")
    parser.add_argument("--padding", default=1, type=int,
                        help="Number of digits for the frame number")
    parser.add_argument("--start", default=1, type=int,
                        help="Start frame to renumber to")
    parser.add_argument("--new_dir",
                        help="New directory for the renamed files. "
                             "Source files will be copied instead of renamed")
    parser.add_argument("-n", "--dryrun",
                        help="dryrun mode to test the rename",
                        action="store_true")
    return parser.parse_args()


def main():
    args = get_args()
    rename_seq.rename_seq(args.path, padding=args.padding, start=args.start,
                          new_dir=args.new_dir, dryrun=args.dryrun)


if __name__ == "__main__":
    main()
